<?php

return [
    [
        'id' => 'one',
        'label' => '90%tile and above',
        'title' => 'Colleges through 90%tile and Above',
        'columns' => [
            ['key' => 'college', 'label' => 'College'],
            ['key' => 'percentile', 'label' => 'Overall %tile'],
            ['key' => 'fees', 'label' => 'Fees (2 years)'],
            ['key' => 'highest', 'label' => 'Highest Package'],
            ['key' => 'average', 'label' => 'Average Package'],
            ['key' => 'companies', 'label' => 'Companies coming on Campus'],
        ],
        'rows' => [
            [
                'college' => 'Xavier Institute of Management, Bhubaneswar (XIMB)',
                'percentile' => '95+',
                'fees' => '21+ Lakhs (MBA BM )',
                'highest' => '30 LPA',
                'average' => '19.53 LPA',
                'companies' => 'Air India, DE Shaw, Accenture, IDBI Bank, IBM, EY.',
                'apply_now' => '#',
            ],
            [
                'college' => 'XLRI Delhi',
                'percentile' => '94+',
                'fees' => '28.6 Lakhs',
                'highest' => '75 LPA',
                'average' => '29.89 LPA',
                'companies' => 'Accenture Strategy, Amazon, Asian Paints, Bajaj Auto, HCL, HUL, Ola, PwC, etc.',
                'apply_now' => '#',
            ],
            [
                'college' => 'XLRI Jamshedpur',
                'percentile' => '94+',
                'fees' => '28.6 Lakhs',
                'highest' => '75 LPA',
                'average' => '29.89 LPA',
                'companies' => 'Accenture Strategy, Amazon, Asian Paints, Bajaj Auto, HCL, HUL, Ola, PwC, etc.',
                'apply_now' => '#',
            ],
        ],
    ],
    [
        'id' => 'two',
        'label' => '80 to 90%tile',
        'title' => 'Colleges through 80 to 90%tile',
        'columns' => [
            ['key' => 'college', 'label' => 'College'],
            ['key' => 'percentile', 'label' => 'Overall %tile'],
            ['key' => 'fees', 'label' => 'Fees (2 years)'],
            ['key' => 'highest', 'label' => 'Highest Package'],
            ['key' => 'average', 'label' => 'Average Package'],
            ['key' => 'companies', 'label' => 'Companies coming on Campus'],
        ],
        'rows' => [
            [
                'college' => 'BIM Trichy: Bharathidasan Institute of Management',
                'percentile' => '85+',
                'fees' => '18 Lakhs',
                'highest' => '20.5 LPA',
                'average' => '12.4 LPA',
                'companies' => 'Barclays, Infosys, City Union Bank, ICICI Prudential, Ford',
                'apply_now' => '#',
            ],
            [
                'college' => 'Xavier Institute of Social Services, Ranchi (XISS)',
                'percentile' => '85+',
                'fees' => '8.90 Lakhs',
                'highest' => '20.50 LPA',
                'average' => '9.40 LPA',
                'companies' => 'HDFC, ICICI Bank, Deloitte India, EY, Emami, MTR Foods.',
                'apply_now' => '#',
            ],
            [
                'college' => 'FORE School of Management, New Delhi (Core)',
                'percentile' => '85+',
                'fees' => '22.24 Lakhs',
                'highest' => '29 LPA',
                'average' => '16.8 LPA',
                'companies' => 'ITC, Nestlé, Asian Paints, HUL, Bacardi, Café Coffee Day, United Breweries, Nivea, Suzuki, Tata Motors, Mahindra, Hero, Hyundai, JK Tyre, Godfrey Phillips, Whirlpool, Vivo',
                'apply_now' => '#',
            ],
            [
                'college' => 'Goa Institute of Management (GIM)',
                'percentile' => '85+',
                'fees' => '20.04 Lakhs',
                'highest' => '32.2 LPA',
                'average' => '15.13 LPA',
                'companies' => 'Accenture, Asian Paints, Deloitte, Capgemini, J.P. Morgan, Vedanta.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Institute of Rural Management, Anand (IRMA)',
                'percentile' => '80+',
                'fees' => '13.60 Lakhs',
                'highest' => '31.16 LPA',
                'average' => '14.14 LPA',
                'companies' => 'Amul, Deloitte, ICICI Bank, KPMG, Big Basket, Dabur.',
                'apply_now' => '#',
            ],
            [
                'college' => 'K J Somaiya Institute of Management',
                'percentile' => '80+',
                'fees' => '20.87 Lakhs',
                'highest' => '28.5 LPA',
                'average' => 'Top 100-17.34 LPA | Top 200-15.8 LPA',
                'companies' => 'Capgemini, TCS, Wipro, Accenture, Infosys',
                'apply_now' => '#',
            ],
            [
                'college' => 'Lal Bahadur Shastri Institute of Management, New Delhi',
                'percentile' => '80+',
                'fees' => '16.5 Lakhs',
                'highest' => '16.67 LPA',
                'average' => '12.24 LPA',
                'companies' => 'Deloitte, Bain & Co, EY GDS, KPMG.',
                'apply_now' => '#',
            ],
            [
                'college' => 'MICA, Ahmedabad',
                'percentile' => '80+',
                'fees' => '26 Lakhs',
                'highest' => '36 LPA',
                'average' => '20.09 LPA',
                'companies' => 'Cognizant, Deloitte, Dalmia Group, Flipkart, Google.',
                'apply_now' => '#',
            ],
            [
                'college' => 'National Insurance Academy Pune',
                'percentile' => '80+',
                'fees' => '11.00 Lakhs',
                'highest' => '22 LPA',
                'average' => '12.3 LPA',
                'companies' => 'Bajaj Allianz, HDFC, TATA AIA, SBI General Insurance',
                'apply_now' => '#',
            ],
            [
                'college' => 'Welingkar Institute of Management, Mumbai',
                'percentile' => '80+',
                'fees' => '14 Lakhs',
                'highest' => '40 LPA',
                'average' => '12.02 LPA',
                'companies' => 'EY, Accenture, Amazon, Barclays, Deloitte USI.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Xavier Institute of Management and Entrepreneurship (XIME)',
                'percentile' => '80+',
                'fees' => '12.50 Lakhs',
                'highest' => '16 LPA',
                'average' => '10.85 LPA',
                'companies' => 'EY, Infosys, Cognizant, Dell, Wipro, Deloitte, Accenture, Gartner.',
                'apply_now' => '#',
            ],
        ],
    ],
    [
        'id' => 'three',
        'label' => '70 to 80%tile',
        'title' => 'Colleges through 70 to 80%tile',
        'columns' => [
            ['key' => 'college', 'label' => 'College'],
            ['key' => 'percentile', 'label' => 'Overall %tile'],
            ['key' => 'fees', 'label' => 'Fees (2 years)'],
            ['key' => 'highest', 'label' => 'Highest Package'],
            ['key' => 'average', 'label' => 'Average Package'],
            ['key' => 'companies', 'label' => 'Companies coming on Campus'],
        ],
        'rows' => [
            [
                'college' => 'NIA Pune',
                'percentile' => '80+',
                'fees' => '11 Lakhs',
                'highest' => '22 LPA',
                'average' => '12.3 LPA',
                'companies' => 'TATA AIA, Accenture, Kotak Bank, HDFC Ergo, Bajaj Allianz',
                'apply_now' => '#',
            ],
            [
                'college' => 'Alliance School of Business, Bangalore',
                'percentile' => '75-80+',
                'fees' => '15 Lakhs',
                'highest' => '38.05 LPA',
                'average' => '8.5 LPA',
                'companies' => 'Amazon, American Express, Biocon, Bosch.',
                'apply_now' => '#',
            ],
            [
                'college' => 'BIM Trichy',
                'percentile' => '75-80+',
                'fees' => '19 Lakhs',
                'highest' => '16 LPA',
                'average' => '10.5 LPA (Mean)',
                'companies' => 'Capgemini, HDFC Bank, Cognizant, Accenture.',
                'apply_now' => '#',
            ],
            [
                'college' => 'IBA Bangalore',
                'percentile' => '75-80+',
                'fees' => '10.32 Lakhs',
                'highest' => '22.26 LPA',
                'average' => '7.96 LPA',
                'companies' => 'Reliance, Colgate, Deloitte, Reckitt, KPMG, Berger Paints, etc.',
                'apply_now' => '#',
            ],
            [
                'college' => 'IIEBM',
                'percentile' => '75-80+',
                'fees' => '7.95 Lakhs',
                'highest' => '30 LPA',
                'average' => '7.5 LPA',
                'companies' => 'Deloitte, Aditya Birla Capital, IDFC, Federal Bank, Godrej, OYO, Swiggy.',
                'apply_now' => '#',
            ],
            [
                'college' => 'ISBR Bangalore',
                'percentile' => '75-80+',
                'fees' => '11 Lakhs',
                'highest' => '16.42 LPA',
                'average' => '8 LPA',
                'companies' => 'Reliance, Colgate, Deloitte, Reckitt, KPMG, Berger Paints, etc.',
                'apply_now' => '#',
            ],
            [
                'college' => 'ISME Bangalore',
                'percentile' => '75-80+',
                'fees' => '10.95 Lakhs',
                'highest' => '14 LPA',
                'average' => '8 LPA',
                'companies' => 'EY, Deloitte, KPMG, Grant Thornton, TCS, Tata Elxsi, Mondelez, Acuity',
                'apply_now' => '#',
            ],
            [
                'college' => 'SOIL Institute of Management',
                'percentile' => '75-80',
                'fees' => 'PGPM 15.3 Lakhs; PGPM HR 14.5 Lakhs; PGDM-15.8 Lakhs',
                'highest' => 'PGPM 22 Lakhs; PGPM-HR 15 Lakhs; PGDM 27 LPA',
                'average' => 'PGPM 11.7 LPA; PGDM 10.7 LPA',
                'companies' => 'ABB, Aditya Birla Capital, Airtel, Canon, Desmania, EIL, HDFC Bank.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Woxsen Business School, Hyderabad',
                'percentile' => '75-80+',
                'fees' => '20.14 Lakhs',
                'highest' => '19 LPA',
                'average' => '9.04 LPA',
                'companies' => 'Deloitte, TCS, Berger Paints, Hexaware, Federal Bank, TVS.',
                'apply_now' => '#',
            ],
            [
                'college' => 'T.A. Pai Management Institute, Manipal (TAPMI)',
                'percentile' => '75+',
                'fees' => '10.03 Lakhs',
                'highest' => '32.02 LPA',
                'average' => '13.84 LPA',
                'companies' => 'AB InBev, Accenture, Deloitte, Gartner, Cognizant.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Welingkar Institute of Management Development and Research, Bangalore',
                'percentile' => '75+',
                'fees' => '14 Lakhs',
                'highest' => '17.63 LPA',
                'average' => '11.11 LPA',
                'companies' => 'Infosys, Wipro, Deloitte, Wells Fargo.',
                'apply_now' => '#',
            ],
            [
                'college' => 'ABBS (Acharya, Bangalore)',
                'percentile' => '70-75+',
                'fees' => '8.9 Lakhs',
                'highest' => '22.5 LPA',
                'average' => '7.5 LPA',
                'companies' => 'Amazon, American Express, Biocon, Bosch.',
                'apply_now' => '#',
            ],
            [
                'college' => 'BIMTECH Greater Noida',
                'percentile' => '70-80+',
                'fees' => '14 Lakhs',
                'highest' => '22 LPA',
                'average' => '10.90 LPA',
                'companies' => '-',
                'apply_now' => '#',
            ],
            [
                'college' => 'FORE School of Management, New Delhi (Non-Core)',
                'percentile' => '75+',
                'fees' => '22.24 Lakhs',
                'highest' => '29 LPA',
                'average' => '16.8 LPA',
                'companies' => 'ITC, Nestlé, Asian Paints, HUL, Bacardi, Café Coffee Day, United Breweries, Nivea, Suzuki, Tata Motors, Mahindra, Hero, Hyundai, JK Tyre, Godfrey Phillips, Whirlpool, Vivo',
                'apply_now' => '#',
            ],
            [
                'college' => 'Fortune Institute of International Business (FIIB) New Delhi',
                'percentile' => '70-80+',
                'fees' => '14 Lakhs',
                'highest' => '22 LPA',
                'average' => '10.90 LPA',
                'companies' => '',
                'apply_now' => '#',
            ],
            [
                'college' => 'K J Somaiya Institute of Management (Non-Core)',
                'percentile' => '70-80+',
                'fees' => '20.87 Lakhs',
                'highest' => '28.5 LPA',
                'average' => 'Top 100-17.34 LPA | Top 200-15.8 LPA',
                'companies' => 'Capgemini, TCS, Wipro, Accenture, Infosys',
                'apply_now' => '#',
            ],
            [
                'college' => 'Lal Bahadur Shastri Institute of Management, New Delhi (Non-core)',
                'percentile' => '70-80+',
                'fees' => '16.5 Lakhs',
                'highest' => '16.67 LPA',
                'average' => '12.24 LPA',
                'companies' => 'Deloitte, Bain & Co, EY GDS, KPMG.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Aditya School of Business Management',
                'percentile' => '70 to 75',
                'fees' => '11 Lakhs',
                'highest' => '25 LPA',
                'average' => '8.64 LPA',
                'companies' => 'Britannia (internship), Marico (live projects), Nomura, Anchor, Bajaj, DTDC, SBI, IndusInd Bank, Shadowfax, 99acres.',
                'apply_now' => '#',
            ],
            [
                'college' => 'BML Munjal',
                'percentile' => '70 to 80',
                'fees' => '14.6 Lakhs',
                'highest' => '14.86 LPA',
                'average' => '9.2 LPA',
                'companies' => 'Capgemini, Amazon, PwC, HP, Cognizant, Accenture, Goldman Sachs, TCS, Deloitte',
                'apply_now' => '#',
            ],
            [
                'college' => 'IILM',
                'percentile' => '70 to 80',
                'fees' => '12.3 Lakhs',
                'highest' => '24 LPA',
                'average' => '8.6 LPA',
                'companies' => 'TCS, HP, Accenture, Goldman Sachs, Capgemini, Deloitte, Amazon, Cognizant, PwC',
                'apply_now' => '#',
            ],
            [
                'college' => 'RCM Bangalore',
                'percentile' => '70 to 80',
                'fees' => '-',
                'highest' => '44 LPA',
                'average' => '8.5 LPA',
                'companies' => 'Deloitte, KPMG, Amazon, Accenture, HDFC Bank, ICICI Bank, Flipkart, Infosys, TCS, HCL, HP, Volvo, Zomato, EY, Capgemini, Tech Mahindra, Federal Bank, Decathlon.',
                'apply_now' => '#',
            ],
            [
                'college' => 'KJ Somaiya',
                'percentile' => '71-75+',
                'fees' => 'MBA & HM-22.19 Lakhs | SM-14.02 Lakhs',
                'highest' => '28.5 LPA',
                'average' => '17.34 LPA',
                'companies' => 'Deloitte, PWC, ICICI Bank, EY, J.P. Morgan, Capgemini, Accenture.',
                'apply_now' => '#',
            ],
            [
                'college' => 'MYRA School of Business',
                'percentile' => '70-75+',
                'fees' => '11 Lakhs',
                'highest' => '16 LPA',
                'average' => '8.64 LPA',
                'companies' => 'Deloitte, Wipro, Federal Bank, Toyota, L&T, TCS, etc.',
                'apply_now' => '#',
            ],
            [
                'college' => 'UPES Dehradun',
                'percentile' => '70-75+',
                'fees' => '16.6 Lakhs',
                'highest' => '29 LPA',
                'average' => '17.1 LPA',
                'companies' => 'Amazon, Accenture, Genpact, HCL, HUL, EY.',
                'apply_now' => '#',
            ],
        ],
    ],
    [
        'id' => 'four',
        'label' => 'Below 70%tile',
        'title' => 'Colleges through Below 70%tile',
        'columns' => [
            ['key' => 'college', 'label' => 'College'],
            ['key' => 'percentile', 'label' => 'Overall %tile'],
            ['key' => 'fees', 'label' => 'Fees (2 years)'],
            ['key' => 'highest', 'label' => 'Highest Package'],
            ['key' => 'average', 'label' => 'Average Package'],
            ['key' => 'companies', 'label' => 'Companies coming on Campus'],
        ],
        'rows' => [
            [
                'college' => 'RCM Bangalore',
                'percentile' => '70',
                'fees' => '-',
                'highest' => '44 LPA',
                'average' => '8.5 LPA',
                'companies' => 'Deloitte, KPMG, Amazon, Accenture, HDFC Bank, ICICI Bank, Flipkart, Infosys, TCS, HCL, HP, Volvo, Zomato, EY, Capgemini, Tech Mahindra, Federal Bank, Decathlon.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Birla Institute of Technology, Mesra',
                'percentile' => '65+',
                'fees' => '6.04 Lakhs',
                'highest' => '51 LPA',
                'average' => '11.57 LPA',
                'companies' => 'Aditya Birla, Indian Oil, Mahindra, Accenture.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Balaji Institute of Modern Management, Pune',
                'percentile' => '60+',
                'fees' => '9.60 Lakhs',
                'highest' => '19 LPA',
                'average' => '7.25 LPA',
                'companies' => 'Accenture, AGS Technologies, Oracle, Cognizant, Credence Analytics Pvt.',
                'apply_now' => '#',
            ],
            [
                'college' => 'Vedica Scholars Programme for Women',
                'percentile' => '60+',
                'fees' => '12.80 Lakhs',
                'highest' => '22 LPA',
                'average' => '10 LPA',
                'companies' => 'Nestle, Zomato, Aditya Birla, Decathlon, KPMG, Gartner, MakeMyTrip, TATA Trust',
                'apply_now' => '#',
            ],
            [
                'college' => 'Institute of Public Enterprise, Hyderabad',
                'percentile' => '50+',
                'fees' => '5.80 Lakhs',
                'highest' => '24.75 LPA',
                'average' => '7.10 LPA',
                'companies' => 'Genpact, Deloitte, TCS, Amazon, Accenture.',
                'apply_now' => '#',
            ],
        ],
    ],
];
